from __future__ import annotations

from typing import Protocol

from app.models.domain import BehaviorEvent, DecisionTrace, Product, SegmentDecision


class PersonalizationRepository(Protocol):
    def save_event(self, event: BehaviorEvent) -> None: ...

    def get_recent_events(self, user_id: str, limit: int = 50) -> list[BehaviorEvent]: ...

    def save_segment(self, user_id: str, segment: SegmentDecision) -> None: ...

    def get_active_segment(self, user_id: str) -> SegmentDecision | None: ...

    def list_products(self) -> list[Product]: ...

    def save_trace(self, trace: DecisionTrace) -> None: ...

    def get_trace(self, trace_id: str) -> DecisionTrace | None: ...

    def get_last_trace_for_user(self, user_id: str) -> DecisionTrace | None: ...
